---
editor_options: 
  markdown: 
    wrap: 72
---

# Acquiring household survey data

This section describes the data sources used for measuring poverty and
inequality as well as how the data are selected and obtained.

## Selection criteria and source of data

For developing countries, the Poverty and Inequality Platform relies on
household surveys carried out by the countries' National Statistical
Offices (NSO). These surveys typically interview a random sample of
households in the country, asking for details about their income and
consumption patterns and much more.

For high-income countries in the European Union (with the exception of
Germany), the data are obtained from the [EU Statistics on Income and
Living Conditions
(EU-SILC)](https://ec.europa.eu/eurostat/web/microdata/european-union-statistics-on-income-and-living-conditions).
EU-SILC data are partly obtained from surveys and partly obtained from
administrative records. For other high-income economies (Australia;
Canada; Germany; Israel; Japan; South Korea; Taiwan, China; and the
United States) data from the [Luxembourg Income Study (LIS)
Database](https://www.lisdatacenter.org) are used. These data rely on
surveys carried out by NSOs or by academic institutions. Data from the
LIS database are also used for high-income countries from the European
Union for years predating EU-SILC.

Occasionally, a survey filling the above criteria is not incorporated into
the platform because the World Bank does not have access to the data,
due to concerns with the survey design or welfare aggregate, or
because the auxiliary data needed (such as [consumer price
indices](#CPIs) and [purchasing power parities](#PPPs])) are
unavailable. Whenever decisions are made to exclude a survey from the
platform, they are done by the Global Poverty Working Group within the
World Bank and the reason for the exclusion of a data point is
summarized in the "What's New" documents.

## Representativeness {#representativeness}

In the majority of cases, the surveys used are representative of all
households in a country. This means that they are based on a random
selection of all households in the country, typically defined from the
most recent census. Two factors prevent these surveys from being
representative of the entire population:

1.  Some individuals do not reside in households and hence are not
    captured by the above frame. This particularly concerns homeless
    people and individuals residing in nursery homes, prisons, and
    displacement camps.
2.  At times, conflicts and extreme weather events prevent the
    enumerators from going to certain parts of the country. In these cases, some geographical areas may be excluded from the survey. The
    2018-19 Nigeria Living Standards Survey, for example, is not
    representative of the Borno state, since parts of the state became
    inaccessible over the course of the survey.

For the purpose of calculating global or regional poverty, the poverty
rates estimated in the surveys are assumed to be representative of the
entire population despite of the two shortcomings above. This is largely
because acquiring any alternative poverty estimate for the missing populations
is challenging. In certain scenarios, the survey design allows the
consumption or income of households not covered to be
[imputed](#imputed), in which case the second problem is addressed.

The PIP also contains some surveys which explicitly only target the
urban or rural part of the population. These surveys are indicated as
[waiting to see how they will appear in PIP]. These surveys are not used
for the purposes of calculating regional or global poverty, with only
one exception. This exception concerns Argentina which has no nationally
representative surveys, but only surveys representative of its urban
population. For the urban population of Argentina, these surveys are
used for the regional and global poverty counts, while the rural
population of Argentina gets the same treatment as [countries for which
we have no data](#nodata).

## How data are obtained

Most of the data for East Asia & Pacific, the Middle East & North
Africa, South Asia, and Sub-Saharan Africa are obtained from countries'
National Statistical Offices. In many low-income countries, the Poverty
and Equity Global Practice of the World Bank is cooperating with the
National Statistical Offices and supporting their efforts to conduct
household surveys and measure poverty. Data are obtained through these
partnerships.

For Latin America and the Caribbean, most of the data are obtained from
CEDLAS's Socio-Economic Database for Latin America and the Caribbean
(SEDLAC).

For most high-income countries data are obtained through the Luxembourg
Income Study or EU-SILC.

All of the data are harmonized by the Poverty and Equity Global Practice
of the World Bank and then passed on to the Poverty and Inequality
Platform.

## Grouped vs. unit record data {#grouped}

In some cases, countries are unwilling to share unit-record data with
the World Bank but they are willing to share grouped data. Grouped data
are aggregated data, often to 5,10, 20 or 100 quantiles of the
distribution. A country might have data on, for example, the mean income of
each percentile or the income share of each percentile. For the purposes
of estimating poverty and inequality, a Lorenz curve is estimated from
these grouped data upon which inequality and poverty can be estimated
(the method behind this is [described here](#treatmentgroups)). Grouped
data are used for Algeria, China, Guyana, Suriname, Turkmenistan,
Trinidad & Tobago, Venezuela, and the United Arab Emirates and more
countries for earlier years. In PIP, grouped data are indicated with a
[wait to see how it will be indicated] while unit-record data is
indicated with a [wait to see how it will be indicated].

## Multiply imputed micro data {#imputed}

At times, unit record data from household surveys are not representative
of all households since conflict or other safety concerns prohibit
enumerators from getting to all areas of a country (see discussion
[here](#representativeness)). In some of these cases, some household
information was collected, either because part of the interviews were
finished before a crisis unfolded, or because shorter interviews without
a full welfare aggregate were conducted in an attempt to minimize safety
risks. In these cases, a full welfare aggregate can be imputed using
statistical models. In an attempt to minimize the uncertainty of such
methods, described in greater detail in [South Sudan and Somalia
papers], they often work by creating multiple imputed datasets,
calculating statistics of interest in each of these dataset, and
averaging over them to acquire a final estimate.

Currently such data are used for South Sudan [insert year],  Somalia 2017 and Zimbabwe 2017.