# Constructing welfare aggregates {#welfareaggregate}

Several different concepts of poverty exist, building on different notions of what a good life -- or in the language of economists, welfare -- entails. Poverty, in short, is the absence of welfare, and individuals are considered poor when their welfare levels fall short of a certain threshold. The Poverty and Inequality Platform (PIP) primarily utilizes a monetary measure of welfare. Monetary welfare is estimated from an aggregation of households' income or from the monetary value of their consumption. We refer to such aggregates jointly as welfare aggregates. This section explains how welfare aggregates are constructed. For a more detailed exposition of the construction of welfare aggregates, see @deaton2002 and @mancini2022.

## Income or consumption {#incomeorconsumption}

Monetary poverty estimates are based on either income or consumption aggregates. Consumption aggregates typically capture household expenditure on a set of items over a given period of time. These usually include purchased, own-produced, exchanged, and gifted food and non-food items (for example clothing, housing---[including imputed rent](#imputedrent)---and the use value of durable consumer goods). Income aggregates capture the value of monetary inflow a household receives or earns over a given period of time. Household surveys usually provide information on labor income (salaries, own-business, and self-employment income), as well as non-labor income coming from pensions, subsidies, transfers, property income, scholarships, etc. Income aggregates in PIP aim to measure disposable income defined as the sum of labor and non-labor income (including transfers) less taxes and contributions. The exact definition and operationalization of income aggregates varies across different [data sources](#selection).

Both income and consumption aggregates do not directly account for important non-monetary aspects of households' welfare such as access to basic services, education, health-care, and infrastructure, which are better captured by other indicators or by [measures of multidimensional poverty](#mpm).

Both income and consumption approaches to measuring monetary poverty have advantages and disadvantages. Countries typically choose the concept that can be more accurately measured and that is more relevant to their context, while balancing concerns about respondent burden in surveys.

The consumption approach is arguably more directly connected to economic welfare. Yet, consumption aggregates require a wide range of questions, detailed price data, and often post-fieldwork adjustments. The design of consumption questionnaires varies widely and, as shown by numerous experiments, can have significant effects on final poverty estimates (see [section on questionnaire design](#questionnaire) below).

Income aggregates, on the other hand, often rely on no more than a handful of questions and can, at times, be verified from other sources. Yet they are difficult to obtain when a large fraction of the population works in the informal sector or is self-employed, which is frequently the case in poorer economies. When households produce their own food with limited market interactions, it is harder to measure income than consumption. Income aggregates also suffer from the disadvantage that incomes might be very low---even negative---in a given period, whereas consumption is smoothed to safeguard against such shocks. Subsistence requires a minimum level of consumption, which is strictly above zero [@worldbank2018].

The differences between income and consumption matter for comparing trends and levels of poverty and inequality. Given that incomes can be very low or negative, poverty rates are typically higher when income is used rather than consumption. For a given poverty rate, poor households also tend to be further below the poverty line when income is used, as explained by the earlier point about very low incomes. Incomes are also more likely than consumption to be very high for a given year, which in conjunction with the very low values means that inequality often is higher when incomes are used rather than consumption.

## Questionnaire design {#questionnaire}

Constructing a welfare aggregate, particularly a consumption aggregate, requires many specific questions to be asked in household surveys. There are many different ways to ask survey respondents about their consumption habits, and how one asks has a significant effect on how people respond. Consumption aggregates are sensitive to whether respondents recall consumption from memory or use consumption diaries, how many and how detailed consumption items are listed, and the time period interviewers ask respondents to recall. @deweerdt2020 provide a recent review of the impact these choices can have on the final poverty estimates.

To give one concrete example, the recall period affects reported consumption through two main channels: memory decay and telescoping. A longer recall period is better at encompassing expenditure on infrequently purchased items, but it can lead to underreporting if respondents forget about past purchases. Despite lower average consumption, measured poverty might be lower under the longer recall period because it captures the purchases of low frequency items of households in the lower parts of the distribution. Short recall periods can mitigate underreporting but can lead to telescoping, where respondents mistakenly report the consumption that took place outside of the reference period.

India provides one example of the relevance of the recall period for poverty estimation. Prior to the 2011/12 Indian National Sample Survey (NSS), the Indian surveys collected information on consumption using a uniform reference period (URP) — where consumption items are recorded based on a recall period of 30 days for all items. Starting with the 2022/23 NSS, items are only collected using a modified mixed reference period (MMRP) -- where consumption items are recorded based on a 7 or 30-day recall for frequently purchased items, 365 days for infrequent purchases. The 2011/12 NSS (Schedule 1 and Schedule 2) collected consumption aggregates using both the URP and the MMRP allowing us to examine the impact on the poverty. The 2011/12 international poverty rate for India based on the 2017 PPPs and using the URP was 22.9 percent compared to 16.2 percent using the MMRP [@castanedaaguilar2025].

Changes in questionnaire design imply that poverty estimates within countries become incomparable. Whenever such changes occur, they are marked in the [comparability database](#comparability).

## Imputed rent {#imputedrent}

During the process of constructing a welfare aggregate, housing is arguably one of the most important and difficult components to include. From a conceptual point of view, housing could be understood as any other durable good: Its present value is not relevant for the analysis of current welfare because purchasing a house is such a large and relatively rare expenditure that it should not be included in the welfare aggregate [@deaton2002]. The objective is instead to measure the value of occupying the dwelling for a month or another limited duration.

Whether the welfare aggregate is based on [consumption or income](#incomeorconsumption), accounting for housing is important. When the welfare aggregate is based on consumption, household surveys usually record the value of rent paid by market tenants. Since rent is the market value of occupying a house for a given period of time, it is feasible and empirically viable to estimate the flow of housing services. Yet, the same information is not available for household owners, even though they also "consume" housing services. By not including the value of housing consumed by owners, it would look like two household with the very same consumption patterns have different welfare just because one pays rent and the other does not. In fact, the market tenant would look better off than the household owner because the consumption of the former is higher than the one of the latter.

When the welfare aggregate is based on income the logic is similar. In this case, the welfare aggregate should be composed of the remuneration of all the assets of the household including labor, capital, and durable goods such as houses [@gasparini2004]. Families that own their housing receive an implicit value that is equivalent to the amount of money they would have to pay in the market if they had to rent a dwelling similar to the one they are currently living in. Hence, to properly account for housing in welfare aggregates, one needs to impute rent for owners.

Several methods exist to impute rent (see @balcazar2017 for a review). Due to the data needs of these approaches, imputed rent is not always computed, leading housing to be excluded from the welfare aggregate. Across the surveys used in PIP, it varies between country and within countries over time whether imputed rent is included. Due to the value of housing services relative to total welfare, this can matter a great deal for poverty [comparability over time](#comparability).

## Within-survey spatial/temporal deflation {#spatialtemporal}

When constructing a welfare aggregate, one is met with the challenge that prices differ geographically within a country and change over the time of the fieldwork. This means that the same level of income can have a different value for different households in the survey, and that households with the same consumption patterns can have very different consumption aggregates if the prices they face differ. To make the welfare aggregates comparable across time and space, spatial and temporal price deflation are needed. Whether or not such deflation is carried out depends on the availability of price data and country-specific practices. Whenever a country switches from not spatially deflating to spatially deflating, this might lead to [incomparable](#comparability) poverty estimates over time.

### Spatial deflation

Suppose a household pays \$1 for a kilo of rice in an urban center, while a rural household in the same country only pays \$0.5 for a similar quality and amount of rice. If one were to assess poverty based on the value of the goods and services consumed without accounting for these price differences, all else being equal, one would conclude that the rural household is poorer than the urban household. Yet, from a welfare perspective, they are equally well off. To properly compare the welfare levels of the two households one needs to account for the differences in price levels that the two households face.

There are several ways to account for spatial price differences. One way is to compare the price of a representative basket of goods across locations and convert household consumption expenditure into the prices of a reference location, such as the capital city or the national average price level.

Currently most surveys from East Asia & Pacific, Latin America & the Caribbean, and Europe & Central Asia are spatially deflated, while it is less common in Sub-Saharan Africa, South Asia, and the Middle East & North Africa. China has rural/urban [purchasing power parities (PPPs)](#PPPs) that are used to deflate welfare aggregates to account for rural/urban price differences within these countries.

### Temporal deflation

Household surveys are often carried out over several months, leading to the possibility that prices evolve notably over this period. If unaccounted for, this means that two households at the same location that have the same consumption patterns but are interviewed at the beginning and the end of the fieldwork may have different consumption aggregates. Accounting for such temporal deflation implies choosing a reference period and deflating all consumption aggregates to that period. This can be a specific year, quarter or month. The exact time chosen for each survey is listed in the appendix table of the most recent What's New document. Temporal deflation within a survey is not carried out in all cases, often because the month of the fieldwork is not available.

Sometimes, a spatio-temporal price index is used to jointly adjust for both spatial and temporal price differences. The household welfare aggregate from the survey conducted in Ghana in 2016-17, for example, is evaluated at 2013 Greater Accra regional prices.

All surveys used by PIP are assigned to a particular year using two variables *year* and *datayear*. If all fieldwork for a survey took place during one calendar year, and relate to the consumption or income of that year, *year* and *datayear* are both equal to this calendar year. When household surveys span two calendar years, the *datayear* noted in the Poverty and Inequality Platform is not an integer. The Gambia, for example, has a datayear of 2015.31. This means that 69% of the fieldwork for this particular survey took place in 2015 while 31% of the fieldwork months took place in 2016. In these cases, the *year* information is the floor of *datayear.* The *datayear* is used for [interpolations](#interpolation), [extrapolations](#extrapolations), and at times, for the [inflation](#CPIs) to convert the welfare vector to constant prices. Notice that in some cases neither the *datayear* nor the *year* align with the year of the survey. For EU-SILC surveys, for example, the income information asked in a survey in a given year relates to income of the previous year. Here, the *datayear* and *year* will both be one year prior to the year the survey was carried out.

## Equivalence scale

All welfare aggregates are converted into per capita terms by dividing the total household welfare with the number of household members. The use of a per capita normalization is standard in the literature on developing countries. Behind the per capita conversion lies an assumption that all household members have equal consumption levels or derive equal welfare from the total household income. This is based on the assumption that there is little scope for economies of size in consumption for poor people.

This assumption can be questioned [@lanjouw1995; @jolliffe2024b]. If household members have different needs, which could be the case if children, for example, require less consumption than adults, then using per capita welfare might be misleading. The assumption would also be violated if household members with the same needs do not get the same share of household income and consumption. Evidence has shown that females often get less than an equal part of household income and consumption (see chapter 5 of @worldbank2018 and references therein). An alternative assumption often used by countries when measuring poverty, is to use an adult equivalence scale. Such a scale defines the consumption need of each household member---often based on age and the household size---relative to a benchmark. Total household welfare is then converted into welfare per adult equivalent household member.

Despite its compelling features, the lack of agreement on which equivalence scale to use across countries and the more difficult interpretation of the final poverty rates have prevented the World Bank from using such numbers for global poverty monitoring thus far. Per capita estimates have the advantage that they have a clear counterpart in national accounts, which matters for [extrapolating](#extrapolations) and [interpolating poverty](#interpolations) estimates to a common reference year.

Though equivalence scales aren't used, it is important to note that each household is weighted by the product of its sampling weight and the household size. The latter implies that the poverty rates show the share of the *population* living in poverty, not the share of *households* living in poverty.

## Bottom coding of welfare {#bottom}

The bottom of consumption and income distributions is typically prone to measurement errors [@ravallion2016]. Zero (or very low) consumption is not plausible, given that a minimum consumption of food is required for human survival. Very low, zero, and even negative incomes are plausible due to negative capital income shocks, negative self-employment income, and more. In many cases, households with negative incomes might be relatively well off, and can cope by drawing down on savings [@hlasny2022]. As such, households with negative incomes might not be living in poverty.

All poverty and inequality indicators in PIP are calculated using income and consumption distributions that drop negative incomes and replace all observations below $\$0.28$ per person per day with $\$0.28$ per person per day [@yonzanF; @jolliffe2025].

Bottom coding distributions do not affect the headcount ratio (all individuals are identified as poor either way) but are relevant for distribution-sensitive measures, such as the Gini index, mean log deviation, poverty gap, Watts index, and the Prosperity Gap. Small positive values can have an extreme influence on distribution-sensitive indices [@cowell2006; @cowell2007].

## Treatment of grouped data {#tgd}

A welfare aggregate is also needed to estimate poverty and inequality from [grouped data](#grouped). Grouped data are consumption or income organized in intervals or bins, such as deciles or percentiles. These bins are used to derive a continuous Lorenz curve, which plots the cumulative welfare share (on the y-axis) against the cumulative population share (on the x-axis). Together with information about mean welfare, the Lorenz curve can be used to construct a full distribution. Two approaches are used to derive a Lorenz function, the general quadratic (GQ) Lorenz function and the Beta Lorenz function [@datt1998]. Both functions are parameterized and estimated. The function that provides the best fit is selected conditional on passing normality and validity tests (see [here](https://github.com/PIP-Technical-Team/wbpip/blob/0cf9aa7bc168400ecf78ae5455f4c4247b841e9d/R/gd_select_lorenz.R#L143-L175) for the code on the tests).

The GQ Lorenz function is estimated using the following specification:

$$
L(1-L) = a(p^2-L) + bL(p-1) + c(p-L),
$$

where $p$ is the cumulative proportion of the population, $L$ is the cumulative proportion of consumption expenditure or income, and $a$, $b$, $c$ are parameter estimates [@datt1998]. The Beta Lorenz function is estimated using the following specification:

$$
L(p) = p - \theta p^\gamma (1-p)^\delta,
$$ where $\theta$, $\gamma$, and $\delta$ are parameter estimates [@datt1998].

After selecting the best approach (either GQ or Beta) for each set of grouped data, a synthetic welfare vector is generated, and it is treated as any unit-record data for poverty and inequality estimation.

## Comparability of estimates {#comparability}

As countries frequently improve the [questionnaire design](#questionnaire) of household surveys and the methodology for the construction of welfare aggregates, poverty estimates over time for a country are not always comparable. In order to guide users about when poverty can be compared over time within a country, PIP's line charts for countries only connect poverty estimates when these are comparable. In addition, PIP contains metadata on the comparability of poverty estimates within countries over time.

The metadata can be accessed through the [PIP API](https://pip.worldbank.org/api), [PIP Stata module](https://github.com/worldbank/pip), or [PIP R package](https://github.com/worldbank/pipr). The variables `comparable_spell` and `survey_comparability` contain the necessary information. The latter has the following logic: The oldest comparable series in each country starts with the value zero (0). When comparability is broken, the value changes to one (1) for the year of the break and it goes on until the comparability is broken again in a subsequent year. The process repeats until the most recent survey data point available.

Within a country, comparability of poverty estimates over time is assumed unless there is a known change to the survey instrument, survey methodology, measurement, or data structure. The assessment of comparability is country-dependent and relies on the accumulation of knowledge from past and current World Bank staff, as well as close dialogue with national data producers with knowledge of survey design and methodology. More documentation of the comparability assessment is available in @atamanov2019.
