# Converting welfare aggregates {#convert}

Welfare aggregates from household surveys are often expressed in national currency units in prices around the time of the fieldwork. To use a [welfare aggregate](#welfareaggregate) from a particular survey to estimate extrme poverty at the [international poverty line](#IPL), the welfare aggregates need to be converted to a unit comparable across time and across countries. To this end, first [Consumer Price Indices (CPIs)](#CPIs) are used to express the aggregates in the same prices within a country. Second, [Purchasing Power Parities (PPPs)](#PPPs) are used to express all welfare aggregates in the same currency by adjusting for price differences across countries.

## Consumer Price Indices (CPIs) {#CPIs}

Consumer price indices (CPIs) summarize the prices of a representative basket of goods and services consumed by households within an economy over a period of time. Inflation (deflation) occurs when there is a positive (negative) change in the CPI between two time periods. With inflation, the same amount of rupees is expected to buy more today than one year from today. CPIs are used to deflate nominal income or consumption expenditure of households so that the welfare of households can be evaluated and compared between two time periods at the same prices.

The primary source of CPI data for the Poverty and Inequality Platform is [IMF's International Financial Statistics (IFS)](https://data.imf.org/?sk=4c514d48-b6ba-49ed-8ab9-52b0c1a0179b) monthly CPI series. The simple average of the monthly CPI series for each calendar year is used as the annual CPI. When IFS data are missing, other sources of CPI data are obtained from [IMFs World Economic Outlook (WEO)](https://www.imf.org/en/Publications/SPROLLs/world-economic-outlook-databases#sort=%40imfdate%20descending) and National Statistical Offices (NSOs), among others. For more details on the different sources of CPI data used for global poverty measurement, see Figure 1 of @lakner2018 and the "What's New" technical notes accompanying PIP updates.

CPI series are rebased to the International Comparison Programme (ICP) reference year, currently 2011.

## Purchasing Power Parities (PPPs) {#PPPs}

Purchasing power parities (PPPs) are used in global poverty estimation to adjust for price differences across countries. PPPs are price indices published by the [International Comparison Program (ICP](https://www.worldbank.org/en/programs/icp)) that measure how much it costs to purchase a basket of goods and services in one country compared to how much it costs to purchase the same basket of goods and services in a reference country, typically the United States. PPP conversion factors are preferred to market exchange rates for the measurement of global poverty because the latter overestimate poverty in developing countries, where non-tradable services are relatively cheap (a phenomenon known as the Balassa-Samuelson-Penn effect). The revised 2011 PPPs are currently used to convert household welfare aggregates, expressed in local currency units in 2011 prices, into a common internationally comparable currency unit. The PPP conversion only affects the cross-country comparison of levels of welfare; the growth in the survey mean for a particular country over time is the same whether it is expressed in constant local currency or in USD PPP.

The PPP estimates used for global poverty measurement are the consumption PPPs from the ICP with a few exceptions. PPPs are imputed for six countries, namely Egypt, Iraq, Jordan, Lao, Myanmar and Yemen, where there are concerns over the coverage and/or quality of the underlying ICP price collection [@atamanov2018; @atamanov2020].

Though PPPs are supposed to be nationally representative, to account for possible urban bias in ICP data collection, separate rural and urban PPPs are computed for China, India, and Indonesia using official national PPPs, the ratio of urban to rural poverty lines, and the urban share in ICP price data collection [@chen2008; @chen2010; @jolliffe2015; @ferreira2016; @atamanov2020].

## Derivation of the international poverty line {#IPL}

Most countries have a national poverty line which summarizes the value of consumption or income per person or per adult equivalent needed to be non-poor. These national poverty lines are typically estimated by National Statistical Offices and reflect country-specific definitions of what it means to be poor. For low and middle-income countries, the lines usually reflect the cost of purchasing a bundle of food items necessary to obtain minimum daily calories to which a basic non-food component is added. For high-income countries the national poverty lines are often relative and are defined relative to the national mean or median income.

To compare poverty across countries one needs a common standard. Hence, national poverty lines, which differ from one country to the next, cannot be used. The international poverty line is an attempt to summarize the national poverty lines of the poorest countries.

Since 1990, the World Bank has derived international poverty lines from the national poverty lines of the poorest countries of the world [@ferreira2016]. In 1990, this resulted in a the "Dollar-a-day" poverty line. Whenever new rounds of PPPs have been released, the nominal value of the international poverty line has been updated. This does not mean that the real value of the international poverty line has changed.

The current international poverty line of \$1.90/day in 2011 PPPs was derived as the mean national poverty line of some of the 15 poorest countries. That is, it represents a typical poverty line of some of the poorest countries in the world. The line is derived by first converting the national poverty lines into PPP-adjusted dollars in the same manner as welfare distributions are converted. This was done by @ravallion2009 who selected the 15 poorest countries with an available national poverty line, ranked by household final consumption expenditure per capita of countries around 2008 when the 2005 PPPs were released. An IPL of \$1.25/day per person, expressed in 2005 PPP dollars was determined as the mean of the national poverty lines of these countries. When the 2011 PPPs were released in 2014, the same 15 national poverty lines were used, but now converted to 2011 PPPs yielding an IPL of \$1.88, which was rounded to \$1.90 [@ferreira2016]. When the 2011 PPPs got revised in 2020, the IPL was similarly updated but remains unchanged at \$1.90 [@atamanov2020; @worldbank2020]. Below is the list of the 15 poorest countries and their national poverty lines denominated in 2005, original 2011, and revised 2011 PPPs.

+---------------+-----------+---------------+-------------------+------------------+
| Country       | Survey    | Poverty line, | Poverty line,     | Poverty line,    |
|               |           |               |                   |                  |
|               | year      | 2005 PPP      | original 2011 PPP | revised 2011 PPP |
+:==============+:==========+:==============+:==================+:=================+
| Chad          | 1995-96   | 0.87          | 1.28              | 1.29             |
+---------------+-----------+---------------+-------------------+------------------+
| Ethiopia      | 1999-2000 | 1.35          | 2.03              | 1.98             |
+---------------+-----------+---------------+-------------------+------------------+
| Gambia, The   | 1998      | 1.48          | 1.82              | 1.81             |
+---------------+-----------+---------------+-------------------+------------------+
| Ghana         | 1998-99   | 1.83          | 3.07              | 3.11             |
+---------------+-----------+---------------+-------------------+------------------+
| Guinea-Bissau | 1991      | 1.51          | 2.16              | 2.08             |
+---------------+-----------+---------------+-------------------+------------------+
| Malawi        | 2004-05   | 0.86          | 1.34              | 1.33             |
+---------------+-----------+---------------+-------------------+------------------+
| Mali          | 1988-89   | 1.38          | 2.15              | 2.13             |
+---------------+-----------+---------------+-------------------+------------------+
| Mozambique    | 2002-03   | 0.97          | 1.26              | 1.24             |
+---------------+-----------+---------------+-------------------+------------------+
| Nepal         | 2003-04   | 0.87          | 1.47              | 1.47             |
+---------------+-----------+---------------+-------------------+------------------+
| Niger         | 1993      | 1.10          | 1.49              | 1.48             |
+---------------+-----------+---------------+-------------------+------------------+
| Rwanda        | 1999-2001 | 0.99          | 1.50              | 1.47             |
+---------------+-----------+---------------+-------------------+------------------+
| Sierra Leone  | 2003-04   | 1.69          | 2.73              | 2.64             |
+---------------+-----------+---------------+-------------------+------------------+
| Tajikistan    | 1999      | 1.93          | 3.18              | 3.35             |
+---------------+-----------+---------------+-------------------+------------------+
| Tanzania      | 2000-01   | 0.63          | 0.88              | 0.88             |
+---------------+-----------+---------------+-------------------+------------------+
| Uganda        | 1993-98   | 1.27          | 1.77              | 1.77             |
+---------------+-----------+---------------+-------------------+------------------+
| **Mean**      |           | **1.25**      | **1.88**          | **1.87**         |
+---------------+-----------+---------------+-------------------+------------------+

## Derivation of other global poverty lines

In addition to the [international poverty line](#IPL), the World Bank uses two higher poverty lines to measure and monitor poverty in countries with a low incidence of extreme poverty. These higher lines, namely \$3.20 and \$5.50 in revised 2011 PPPs, are derived in @jolliffe2016 as the median values of national poverty lines of lower- and upper-middle income countries, respectively. When replicating the derivation of these lines with the revised 2011 PPPs, the estimates for the \$3.20 lines does not change, while the \$5.50 line increases by approximately \$0.15 [@atamanov2020]. The World Bank decided to keep all the global poverty lines unchanged, including the \$5.50 line. These poverty lines are goalposts to be held fixed over time and they have become widely used, so there is a cost to revising them frequently. The global poverty lines were chosen with the PPPs available at the time using a reasonable method; thereafter we view them as fixed parameters to monitor progress in different parts of the global distribution of income or consumption.
