# Generating survey estimates of poverty and inequality {#surveyestimates}

Welfare aggregates from household surveys are expressed in national currency
units in prices around the time of the fieldwork. To use a [welfare
aggregate](#welfareaggregates) from a particular survey to estimate
international poverty, the welfare aggregates need to be converted to a unit
comparable across time and across countries. To this end, first [Consumer Price
Indices (CPIs)](#CPIs) are used to express the aggregates in the same prices
within a country. Second, [Purchasing Power Parities (PPPs)](#PPPs) are used to
express all welfare aggregates in the same currency while adjusting for price
differences across countries.

## Consumer Price Indices (CPIs) {#CPIs}

Consumer price indices (CPIs) summarize the prices of a representative basket of
goods and services consumed by households within an economy over a period of
time. Inflation (deflation) occurs when there is a positive (negative) change in
the CPI between two time periods. With inflation, the same amount of rupees is
expected to buy more today than one year from today. CPIs are used to deflate
nominal income or consumption expenditure of households, so that the welfare of
households can be evaluated and compared between two time periods at the same
prices.

The primary source of CPI data for the Poverty and Inequality Platform is [IMF's
International Financial Statistics
(IFS)](https://data.imf.org/?sk=4c514d48-b6ba-49ed-8ab9-52b0c1a0179b) monthly
CPI series. The simple average of the monthly CPI series for each calendar year
is used as the annual CPI. When IFS data are missing, other sources of CPI data
are obtained from [IMFs World Economic Outlook
(WEO)](https://www.imf.org/en/Publications/SPROLLs/world-economic-outlook-databases#sort=%40imfdate%20descending)
and National Statistical Offices (NSOs), among others. For more details on the
different sources of CPI data used for global poverty measurement, see Figure 1
of @lakner2018 and "What's New" technical notes accompanying PIP updates (e.g.
the latest [September 2020 PovcalNet Update: What's
New](https://blogs.worldbank.org/opendata/september-2020-global-poverty-update-world-bank-new-annual-poverty-estimates-using-revised)).

CPI series are expressed in the prices of the International Comparison Programme
(ICP) reference year, currently 2011.

## Purchasing Power Parities (PPPs) {#PPPs}

Purchasing power parities (PPPs) are used in global poverty estimation to adjust
for price differences across countries. PPPs are price indices published by the
[International Comparison Program
(ICP](https://www.worldbank.org/en/programs/icp)) that measure how much it costs
to purchase a basket of goods and services in one country compared to how much
it costs to purchase the same basket of goods and services in a reference
country, typically the United States. PPP conversion factors are preferred to
market exchange rates for the measurement of global poverty because the latter
overestimates poverty in developing countries, where non-tradable services are
relatively cheap (i.e., the Balassa-Samuelson-Penn effect). The revised 2011
PPPs are currently used to convert household welfare aggregates, originally
expressed in local currency units in 2011 prices, into a common internationally
comparable currency unit. It is important to note that the PPP conversion only
affects the cross-country comparison of levels of welfare; the growth in the
survey mean for a particular country is the same whether it is expressed in
constant local currency or in USD PPP.

The PPP estimates used for global poverty measurement are the consumption PPPs
from the ICP with a few exceptions. PPPs are imputed for six countries, namely
Egypt, Iraq, Jordan, Lao, Myanmar and Yemen, where there are concerns over the
coverage and/or quality of the underlying ICP price collection [@atamanov2018;
@atamanov2020].

Though PPPs are supposed to be nationally representative, to account for
possible urban bias in ICP data collection, separate rural and urban PPPs are
computed for China, India and Indonesia using official national PPPs, the ratio
of urban to rural poverty line, and the urban share in ICP price data collection
[@chen2008; @chen2010; @jolliffe2015; @ferreira2016; @atamanov2020].

## Derivation of the international poverty line {#IPL}

Most countries have a national poverty line which summarizes the value of
consumption per person or per adult equivalent needed to not live in poverty.
These national poverty lines are typically estimated by National Statistical
Offices and reflect country-specific definitions of what it means to be poor.
For low and middle-income countries, the lines usually reflect the cost of
purchasing a bundle of food items necessary to obtain minimum daily calories to
which a basic non-food component is added. For high-income countries the
national poverty lines are often relative and are defined relative to the
national mean or median income.

To compare poverty across countries one needs a common standard. Hence, national
poverty lines, which differ from one country to the next, cannot be used. The
international poverty line (IPL) is an attempt to summarize the national poverty
lines of the poorest countries.

Since 1990, the World Bank has derived international poverty lines from the
national poverty lines of the poorest countries of the world [@ferreira2016]. In
1990, this resulting in a the "Dollar-a-day" poverty line. Whenever new rounds
of PPPs have been released the nominal value of the international poverty line
has been updated. This does not mean that the real value of the international
poverty line has changed.

The current international poverty line of \$1.90/day in 2011 PPPs was derived as
the mean national poverty line of some of the 15 poorest countries. That is, it
represents a typical poverty line of some of the poorest countries in the world.
The line is derived by first converting the national poverty lines into
PPP-adjusted dollars in the same manner as welfare distributions are converted.
This was done by @ravallion2009 who selected the 15 poorest countries with an
available national poverty line, ranked by household final consumption
expenditure per capita of countries around 2008 when the 2005 PPPs were
released. An IPL of \$1.25/day per person, expressed in 2005 PPP dollars was
determined as the mean of the national poverty lines of these countries. When
the 2011 PPPs were released in 2014, the same 15 national poverty lines were
used, but now converted to 2011 PPPs yielding an IPL of \$1.88, which was
rounded to \$1.90 [@ferreira2016]. When the 2011 PPPs got revised in 2020, the
IPL was similarly updated but remains unchanged at \$1.90 [@atamanov2020;
@worldbank2020]. Below is the list of the 15 poorest countries and their
national poverty lines denominated in 2005, original 2011 and revised 2011 PPPs.

+--------------+----------+--------------+------------------+------------------+
| Country      | Survey   | Poverty      | Poverty line,    | Poverty line,    |
|              |          | line,        |                  |                  |
|              | year     |              | original 2011    | revised 2011 PPP |
|              |          | 2005 PPP     | PPP              |                  |
+:=============+:=========+:=============+:=================+:=================+
| Chad         | 1995-96  | 0.87         | 1.28             | 1.29             |
+--------------+----------+--------------+------------------+------------------+
| Ethiopia     | 1        | 1.35         | 2.03             | 1.98             |
|              | 999-2000 |              |                  |                  |
+--------------+----------+--------------+------------------+------------------+
| Gambia, The  | 1998     | 1.48         | 1.82             | 1.81             |
+--------------+----------+--------------+------------------+------------------+
| Ghana        | 1998-99  | 1.83         | 3.07             | 3.11             |
+--------------+----------+--------------+------------------+------------------+
| G            | 1991     | 1.51         | 2.16             | 2.08             |
| uinea-Bissau |          |              |                  |                  |
+--------------+----------+--------------+------------------+------------------+
| Malawi       | 2004-05  | 0.86         | 1.34             | 1.33             |
+--------------+----------+--------------+------------------+------------------+
| Mali         | 1988-89  | 1.38         | 2.15             | 2.13             |
+--------------+----------+--------------+------------------+------------------+
| Mozambique   | 2002-03  | 0.97         | 1.26             | 1.24             |
+--------------+----------+--------------+------------------+------------------+
| Nepal        | 2003-04  | 0.87         | 1.47             | 1.47             |
+--------------+----------+--------------+------------------+------------------+
| Niger        | 1993     | 1.10         | 1.49             | 1.48             |
+--------------+----------+--------------+------------------+------------------+
| Rwanda       | 1        | 0.99         | 1.50             | 1.47             |
|              | 999-2001 |              |                  |                  |
+--------------+----------+--------------+------------------+------------------+
| Sierra Leone | 2003-04  | 1.69         | 2.73             | 2.64             |
+--------------+----------+--------------+------------------+------------------+
| Tajikistan   | 1999     | 1.93         | 3.18             | 3.35             |
+--------------+----------+--------------+------------------+------------------+
| Tanzania     | 2000-01  | 0.63         | 0.88             | 0.88             |
+--------------+----------+--------------+------------------+------------------+
| Uganda       | 1993-98  | 1.27         | 1.77             | 1.77             |
+--------------+----------+--------------+------------------+------------------+
| **Mean**     |          | **1.25**     | **1.88**         | **1.87**         |
+--------------+----------+--------------+------------------+------------------+

## Derivation of other global poverty lines

In addition to the [international poverty line](#IPL), the World Bank uses two
higher poverty lines to measure and monitor poverty in countries with a low
incidence of extreme poverty. These higher lines, namely \$3.20 and \$5.50 in
revised 2011 PPPs, are derived in @jolliffe2016 as the median values of national
poverty lines of lower- and upper-middle income countries, respectively. When we
replicate the derivation of these lines with the revised 2011 PPPs, the
estimates for the \$1.90 and \$3.20 lines do not change, while the \$5.50 line
increases by approximately \$0.15 [@atamanov2020]. The World Bank has decided to
keep all the global poverty lines unchanged, including the \$5.50 line. These
poverty lines are goalposts to be held fixed over time and they have become
widely used, so there is a cost to revising them frequently. The global poverty
lines were chosen with the PPPs available at the time using a reasonable method;
thereafter we view them as fixed parameters to monitor progress in different
parts of the global distribution of income or consumption.

## Poverty measures {#povertymeasures}

Armed with welfare distributions expressed in 2011 PPPs and an international
poverty line, poverty and inequality can be calculated and compared across
countries and over time. The poverty and inequality measures used in PIP for
micro data are mainly based on formulae in @haughton2009, while the poverty and
inequality measures estimated from grouped data are mainly based on formulae in
@datt1998.

**Poverty headcount ratio**: The poverty headcount ratio ($P_0$) is a measure of
the proportion of the population that is counted as poor. The poverty headcount
index is obtained from micro data with the following
expression:$$ P_0 = \frac{1}{N} \sum_{i=1}^{N} I (y_i < z), $$

where $N$ is the total population size, $y_i$ is welfare of individual $i$, $z$
is the poverty line, and $I(.)$ is an indicator function that takes on the value
1 if the bracketed expression is true or 0 otherwise. You can find the source
code where this calculation is carried out
[here](https://github.com/PIP-Technical-Team/wbpip/blob/master/R/md_compute_poverty_stats.R).
[[Aleksander]{style="color:red"}: would it be possible to hyperlink 'here' to
the exact lines of the code? [akin to what Andres does in
<https://povcalnet-team.github.io/Povcalnet_internal_guidelines/prepare.html>,
search for "In particular, you can see these lines for GDP")]

For grouped data, the poverty headcount is obtained using the following
expression:

$$
P_0 = - \frac{1}{2m}[n + r(b+2z/\mu)((b+2z/\mu)^2)-m)^{-1/2}],
$$

where $m$ = $b^2 - 4a$, $n = 2be - 4c$, $r = (n^2 - 4me^2)^{1/2}$,
$e = -(a + b + c + 1)$, $z$ is the poverty line, $\mu$ is mean welfare, and
$a, b, c$ are the parameter estimates of the GQ Lorenz function (source code).
If the Beta Lorenz function is used, the poverty headcount is estimated using
the expression below:

$$
\theta {P_0}^\gamma (1 - {P_0})^\delta \left[\frac{\gamma}{P_0} - \frac{\delta}{(1 - {P_0})}\right] = 1 - \frac{z}{\mu}
$$

where where $\theta$, $\delta$, and $\gamma$ are parameter estimates (see
[section on treatment of grouped data](#tgd) the GQ and Beta Lorenz functions).

**Poverty gap index**: The poverty gap index ($P_1$) is a measure that adds up
the extent to which individuals on average fall below the poverty line (i.e. the
depth of poverty), and expresses it as a percentage of the poverty line. The
poverty gap index is obtained from micro data with the following expression:

$$ P_1 = \frac{1}{N} \sum_{i=1}^{N} \frac{G_i}{z} $$ with
$G_i = (z - y_i) × I (y_i < z)$, where $G_i$ is defined as the poverty gap (i.e.
poverty line ($z$) less welfare ($y_i$)) of poor individuals; the gap is
considered to be zero for everyone else. The poverty gap index shows the minimum
cost per capita of eliminating poverty using targeted transfers, expressed as a
percentage of the poverty line (source code: [micro
data](https://github.com/PIP-Technical-Team/wbpip/blob/master/R/md_compute_poverty_stats.R)).

For grouped data, the poverty gap index is obtained using the following
expression:

$$
P_1 = P_0 - (\mu/z)L(P_0)
$$

with all variables defined as before (source code: [grouped
data](https://github.com/PIP-Technical-Team/wbpip/blob/master/R/gd_compute_pip_stats_lq.R)).
The expression holds for both GQ and Beta Lorenz functions.

**Poverty severity index**: The poverty severity index ($P_2$) is a measure of
the weighted sum of poverty gaps (as a proportion of the poverty line), where
the weights are the proportionate poverty gaps themselves. The poverty severity
index is obtained from micro data with the following expression:

$$ P_1 = \frac{1}{N} \sum_{i=1}^{N} \left(\frac{G_i}{z} \right)^2 $$

with all variables defined as before. Also known as the squared poverty gap
index, the poverty severity index accounts for inequality among the poor (source
code: [micro
data](https://github.com/PIP-Technical-Team/wbpip/blob/master/R/md_compute_poverty_stats.R)).

With the GQ Lorenz function, the poverty severity index is obtained from grouped
data using the following expression:

$$
P_2 = 2(P_1) - P_0 - \left(\frac{\mu}{z}\right)^2 \left[aP_0 + bL(P_0) - \left(\frac{r}{16}\right)ln \left(\frac{1 - P_0/s_1}{1 - P_0/s_2}\right)     \right],
$$

where $s_1 = (r- n)/(2m)$, $s_2 = -(r + n)/(2m)$, and all other variables are
defined as before (source code: [grouped
data](https://github.com/PIP-Technical-Team/wbpip/blob/master/R/gd_compute_pip_stats_lq.R)).
With the the Beta Lorenz function, the poverty severity index is given as:

$$
P_2 = (1 -\mu/z)  \left[ 2P_1 - (1- \mu/z) P_0) \right] \\ \ \ \ \ \ \ \ \ \ \ \ \ \ \ + \theta^2 \left(\frac{\mu}{z}\right)^2\left[\gamma^2B(P_0,2\gamma-1,2\delta+1) \\ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ - 2\gamma\delta B(P_0,2\gamma,2\delta) + \delta^2 B(P_0,2\gamma + 1,2\delta-1) \right]
$$

with

$$
B(k,r,s) = \int_0^k p^{r-1}(1 - p)^{s - 1} ~dp
$$

where $k$, $r$, $s$ are parameters and all other notations here are defined as
before for the Beta Lorenz function.

**The Watts index**: The Watts index ($W$) is also an inequality-sensitive
poverty measure that is given as:

$$ W  = \frac{1}{N} \sum_{i=1}^{q} ln \left(\frac{z}{y_i} \right), $$

where $N$ individuals in the population are indexed in ascending order of
welfare, and the sum is taken over $q$ individuals whose welfare, $y_i$, falls
below the poverty line $z$. This formula applies for both micro and grouped data
(source code: [micro
data](https://github.com/PIP-Technical-Team/wbpip/blob/master/R/md_compute_poverty_stats.R)
and [grouped
data](https://github.com/PIP-Technical-Team/wbpip/blob/master/R/gd_compute_pip_stats_lq.R)).
It also holds for both the GQ and Beta Lorenz functions, which are evaluated at
the poverty line $z$ and other percentiles $y_i$. A percentile is given as the
product of the mean and the first derivative of the GQ or Beta Lorenz function
at the respective rank in the distribution (The first derivatives of the GQ and
Beta Lorenz functions are defined below). An item for discussion regarding the
**Watts index** and the Mean Log Deviation (**MLD**) is the treatment of zero
values in the welfare distribution given that the logarithm zero is not defined.
As explained in section \@ref(incomeorconsumption), PIP's current practice is to
drop observations with negative welfare, while zeros are included when the
welfare distribution is based on income. One approach is to transform the zeros
by either maintaining the same mean of the distribution or by adjusting it.
Another solution is to exclude the zeros from the sample, but that would create
inconsistencies with other poverty and inequalities measures that use the whole
sample like the FGT family or the Gini index. As this text is being written
(`r format(Sys.time(), "%B, %Y")`), the PIP team is doing research on the best
way to address this problem. However, for the sake of consistency with previous
releases of this indicator, it has been decided to opt of the second option,
excluding the zero values from the sample.

## Inequality measures {#inequalitymeasures}

**Gini index**: The Gini index is derived from the Lorenz curve, which plots the
cumulative welfare share (on the y-axis) against the cumulative population share
(on the x-axis). A 45-degree line is defined over the Lorenz curve as a line of
perfect equality. The Gini index is the area between the line 45-degree line and
the Lorenz curve (multiplied by 100). Let $A$ be the area between the 45-degree
line and the Lorenz curve, and let $B$ be the area under the Lorenz curve. The
Gini coefficient is given as: $\frac{A}{A + B}= 2A$ (since $A + B = 0.5$).

Formally, if $x_i$ is a point on the x-axis, and $y_i$ a point on the y-axis,
then

$$ Gini = 100*(1 - \sum_{i=1}^{N} (x_i - x_{i-1})(y_i + y_{i-1}))
.
$$

When there are $N$ equal intervals on the x-axis.

The Gini index ranges from 0 (perfect equality) to 100 (complete inequality)
(source code: [micro
data](https://github.com/PIP-Technical-Team/wbpip/blob/master/R/md_compute_gini.R)).

With the GQ Lorenz function, the Gini index is obtained from grouped data using
the following expression:

$$
Gini = 100*\begin{cases}
 \frac{e}{2} - \frac{n(b + 2)}{4m} + \frac{r^2}{8m\sqrt{-m}} \left[\sin^{-1} \frac{(2m + n)}{r} - \sin^{-1}\frac{n}{r} \right] & \text{if $m<0$} \\ 
 \frac{e}{2} - \frac{n(b + 2)}{4m} + \frac{r^2}{8m\sqrt{m}} ln\left[\text{abs}\left( \frac{2m + n + 2\sqrt{m}(a + c - 1)}{n - 2e\sqrt{m}}\right) \right]  & \text{if $m>0$}
 \end{cases} 
 $$

with all parameters defined as before (source code: [grouped
data](https://github.com/PIP-Technical-Team/wbpip/blob/master/R/gd_compute_pip_stats_lq.R)).

With the Beta Lorenz function, the Gini index is given as:

$$
Gini = 100 * 2\theta B(1 + \gamma, 1 + \delta)
$$

Note that $B(1 + \gamma, 1 + \delta)$ is the Beta function
$\int_0^1 p^\gamma (1 - p)^\delta ~dp$.

**Mean log deviation**: The mean log deviation (MLD) belongs to the family of
generalized entropy (GE) inequality measures. It is given as:

$$ MLD  = \frac{1}{N} \sum_{i=1}^{N} ln \left(\frac{μ}{y_i} \right)*100, $$

where $N$ is the total population size, $μ$ is the mean welfare per person, and
$y_i$ is welfare of individual $i$. The mean log deviation has a minimum value
of 0 (perfect equality) and has no upper bound. This formula applies for both
micro and grouped data (source code: [micro
data](https://github.com/PIP-Technical-Team/wbpip/blob/master/R/md_compute_mld.R)
and [grouped
data](https://github.com/PIP-Technical-Team/wbpip/blob/master/R/gd_compute_pip_stats_lq.R)).
It also holds for both the GQ and Beta Lorenz functions, which are evaluated at
the poverty line $z$ and other percentiles $y_i$. A percentile is given as the
product of the mean and the first derivative of the GQ or Beta Lorenz function
at the respective rank in the distribution (The first derivatives of the GQ and
Beta Lorenz functions are defined below). In the same vein of the Watts Index,
the MLD suffers from being undefined when there are zero values in the
distribution. As this text is being written (`r format(Sys.time(), "%B, %Y")`),
the PIP is researching on the best approach to deal with this problem. For now,
however, it has been decided to transform the zeros for ones in order to include
the same sample size as the one used in other inequality measures. We
acknowledge that this decision is not optimal, but at least it is consistent
with what as been done in the past.

**Polarization**: The polarization index ($P$) measures the extent to which the
distribution of welfare is "spread out" and bi-modal. It is given as:

$$
P =  \frac{2(\mu^* - \mu^L)}{m},
$$

where $\mu^*$ is the distribution-correction mean (i.e. $\mu(1 - Gini/100)$),
$\mu^L$ is the mean of the poorest half of the population, and $m$ is the
median. Like the Gini coefficient, the polarization index ranges from 0 (no
polarization) to 1 (complete polarization). The polarization index is based on
@wolfson1994 and @ravallion1996. This formula applies for both micro and grouped
data (source code: [micro
data](https://github.com/PIP-Technical-Team/wbpip/blob/master/R/md_compute_polarization.R)
and [grouped
data](https://github.com/PIP-Technical-Team/wbpip/blob/master/R/gd_compute_pip_stats_lq.R)).

**Median**: The median is the amount of welfare per capita that divides the
distribution into two equal halves. For micro data, the median is estimated as:

$$
Med = \begin{cases}
 Y \left[\frac{n}{2}\right] & \text{if $n$ is even} \\ 
   \left(Y\left[\frac{n - 1}{2} \right] + Y \left[\frac{n + 1}{2} \right]\right) &  \text{if $n$ is odd}
 \end{cases} 
 $$

where $Y$ is the ordered list of welfare per capita in the sample, and $n$ is
the sample size.

For grouped data, the median is estimated as:

$$
Med = \mu L^{'}(0.5)
$$

where $\mu$ is the mean and $L^{'}(0.5)$ is the first derivative of the GQ or
Beta Lorenz function at the 50th percentile.

The first derivative of the GQ Lorenz function is given as:

$$
L^{'}(p) = -\frac{b}{2} - \frac{(2mp + n)(mp^2 + np + e^2)^
{-1/2}}{4}
$$

with all variables and parameter estimates as previously defined.

The first derivative of the Beta Lorenz function is given as:

$$
L^{'}(p) = 1 - \theta p^\gamma (1 - p)^\delta \left[\frac{\gamma}{p} - \frac{\delta}{1 - p}\right]
$$

with all variables and parameter estimates as previously defined.

**Decile shares**: Imagine that we order all households according to their
welfare per capita, such that the first decile contains the 10% of the
population with the lowest welfare and so on. Decile shares measure the share of
total welfare going to each decile. Formally, the decile share of decile $d$ is
given by:

$$ decileshare_d= \frac{\sum_{i \in d} {y_i}}{\sum_{i=1}^{N} {y_i}} ,  d \in \{1,2,..,10 \} $$

This formula holds for both micro and grouped data. For grouped data, welfare
per capita $y_i$ is the product of the mean and the first derivative of the GQ
or Beta Lorenz function at the respective rank in the distribution.
